<?php

/**
 * --- BEGIN AutoGenerated by tool/generateProperties ---
 *
 * This is the model class for table 'page_trail'
 *
 * @method PageTrail with() with()
 * @method PageTrail find() find($condition, array $params = array())
 * @method PageTrail[] findAll() findAll($condition = '', array $params = array())
 * @method PageTrail findByPk() findByPk($pk, $condition = '', array $params = array())
 * @method PageTrail[] findAllByPk() findAllByPk($pk, $condition = '', array $params = array())
 * @method PageTrail findByAttributes() findByAttributes(array $attributes, $condition = '', array $params = array())
 * @method PageTrail[] findAllByAttributes() findAllByAttributes(array $attributes, $condition = '', array $params = array())
 * @method PageTrail findBySql() findBySql($sql, array $params = array())
 * @method PageTrail[] findAllBySql() findAllBySql($sql, array $params = array())
 *
 * Properties from relation
 * @property User $user
 * @property AuditTrail[] $auditTrail
 * @property integer $auditTrailCount
 *
 * Properties from table fields
 * @property integer $id
 * @property string $link
 * @property integer $user_id
 * @property string $ip
 * @property string $post
 * @property string $get
 * @property string $files
 * @property string $session
 * @property string $server
 * @property string $cookie
 * @property string $referrer
 * @property string $redirect
 * @property string $app_version
 * @property string $yii_version
 * @property integer $audit_trail_count
 * @property number $start_time
 * @property number $end_time
 * @property number $total_time
 * @property integer $memory_usage
 * @property integer $memory_peak
 * @property datetime $created
 * @property integer $preserve
 *
 * --- END AutoGenerated by tool/generateProperties ---
 */
class PageTrail extends ActiveRecord
{
    /**
     * @var
     */
    public $model;

    /**
     * @var
     */
    public $model_id;

    /**
     * @var bool
     */
    public $ignoreClearCache = true;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className
     * @return PageTrail the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'page_trail';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return array(
            array('id, user_id, link, created, app_version, yii_version, audit_trail_count, total_time, memory_usage, memory_peak, model, model_id', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        return array(
            'user' => array(
                self::BELONGS_TO,
                'User',
                'user_id',
            ),
            'auditTrail' => array(
                self::HAS_MANY,
                'AuditTrail',
                'page_trail_id',
            ),
            'auditTrailCount' => array(
                self::STAT,
                'AuditTrail',
                'page_trail_id',
            ),
        );
    }

    /**
     * @param array $extraArgs
     * @return array url to view the model
     */
    public function getUrl($extraArgs = array())
    {
        return url('/pageTrail/view', array_merge(array(
            'id' => $this->id,
        ), (array)$extraArgs));
    }

    /**
     * @return string
     */
    public function getLink()
    {
        return l('pageTrail-' . $this->id, $this->getUrl());
    }

    /**
     * @return string
     */
    public function getLinkString()
    {
        $link = $this->link;
        $path = Yii::app()->getRequest()->getHostInfo() . bu();
        if (strpos($link, $path) === 0) {
            $link = substr($link, strlen($path));
        }
        if (strlen($link) < 64)
            return $link;
        return substr($link, 0, 64) . '...';
    }

    /**
     * @static
     * @param $linkGiven
     * @return string
     */
    static function reverseLinkString($linkGiven)
    {
        if (strpos($linkGiven, '/') === 0) {
            $path = Yii::app()->getRequest()->getHostInfo() . bu();
            $result = $path . $linkGiven;
            return $result;
        }
        else {
            return $linkGiven;
        }
    }

    /**
     *
     */
    public function recordPageTrail()
    {
        //saving is done in updatePageTrail() pageTrail->save() function kind of thing
        //$this->created_gmtime = gmdate('Y-m-d h:i:s');
        $this->created = date('Y-m-d H:i:s');
        //$this->user_id = user()->id;
//        $this->session = $this->getShrinkedSession();
//        if (Yii::app() instanceof CWebApplication) {
//            $this->link = app()->getRequest()->getHostInfo() . app()->getRequest()->getUrl();
//            if (isset($_SERVER['REMOTE_ADDR'])) {
//                $this->ip = $_SERVER['REMOTE_ADDR'];
//            }
//            if (isset($_SERVER['HTTP_REFERER'])) {
//                $this->referrer = $_SERVER['HTTP_REFERER'];
//            }
//        }
//        else {
//            $this->link = 'yiic ';
//            if (isset($_SERVER['argv'])) {
//                $argv = $_SERVER['argv'];
//                array_shift($argv);
//                $this->link = implode(' ', $argv);
//            }
//        }
//        $this->app_version = Setting::item('core', 'app_version');
//        $this->yii_version = Setting::item('core', 'yii_version');
        Setting::item('core', 'xxx');
        $this->start_time = $_ENV['_start'];

        $this->removePasswords();
        //serialize , compress and base64encode
        $this->post = $this->pack('post');
        $this->get = $this->pack('get');
        $this->cookie = $this->pack('cookie');
        $this->server = $this->pack('server');
        $this->session = $this->pack('session');
        $this->files = $this->pack('files');
        $this->save();
        static_id('page_trail_id', $this->id); // used for AuditTrail tracking

        // update the user id after the first save
        $this->user_id = user()->id;
        $this->save();
    }

    /**
     *
     */
    function removePasswords()
    {
        $post = $_POST;
        $get = $_GET;
        $server = $_SERVER;
        $passwordRemovedFromGet = self::removedValuesWithPasswordKeys($get);
        $passwordRemovedFromPost = self::removedValuesWithPasswordKeys($post);
        self::removedValuesWithPasswordKeys($server);
        $this->get = $get;
        $this->post = $post;
        $this->files = $_FILES;

        if (!$passwordRemovedFromGet && !$passwordRemovedFromPost) {
            $this->server = $server;
        }
        if ($passwordRemovedFromGet) {
            $this->link = '';
        }
        $this->cookie = $_COOKIE;
    }

    /**
     * @param $attribute
     * @return string
     */
    function pack($attribute)
    {
        $value = $this->$attribute;
        //already packed
        @$alreadyDecoded = is_array(unserialize(gzuncompress(base64_decode($value))));
        if ($alreadyDecoded) {
            echo "<br/> already decoded  <br/>\r\n";
            return;
        }
        $value = serialize($value);
        $value = gzcompress($value);
        $value = base64_encode($value);
        return $value;
    }

    /**
     * @param $attribute
     * @return mixed
     */
    function unpack($attribute)
    {
        @$value = unserialize($this->$attribute);
        if ($value !== false) {
            $this->$attribute = $value;
            return false;
        }
        $value = base64_decode($this->$attribute);
        if (!$value) {
            return false;
        }

        @$value = gzuncompress($value);
        if ($value === false) {
            $this->$attribute = "could not uncompress [" . var_dump($value) . "]";
            return false;
        }
        @$value = unserialize($value);
        if ($value === false) {
            $this->$attribute = "could not unserialize [" . var_dump($value) . "]";
        }
        return $value;
    }

    /**
     * @static
     * @param $array
     * @return bool
     */
    static function removedValuesWithPasswordKeys(&$array)
    {
        if (!$array) {
            return false;
        }
        $removed = false;
        foreach ($array as $key => $value) {
            if (stripos($key, 'password') !== false) {
                $array[$key] = 'Possible password removed';
                $removed = true;
            }
            elseif (stripos($key, 'PHP_AUTH_PW') !== false) {
                $array[$key] = 'Possible password removed';
                $removed = true;
            }
            else {
                if (is_array($value)) {
                    $removedChild = self::removedValuesWithPasswordKeys($value);
                    if ($removedChild) {
                        $array[$key] = $value;
                        $removed = true;
                    }
                }
            }
        }
        return $removed;
    }

    /**
     *
     */
    protected function updatePageTrail()
    {
        $headers = headers_list();
        foreach ($headers as $header) {
            if (strpos(strtolower($header), 'location:') === 0) {
                $this->redirect = trim(substr($header, 9));
            }
        }
        $this->memory_usage = memory_get_usage();
        $this->memory_peak = memory_get_peak_usage();
        $this->end_time = microtime(true);
        $this->total_time = $this->end_time - $this->start_time;
        $this->audit_trail_count = $this->auditTrailCount;
        $this->save();
    }

    /**
     * @return mixed
     */
    public function getShrinkedSession()
    {
        $serialized = '';
        if (isset($_SESSION)) {
            $serialized = serialize($_SESSION);
        }
        if (strlen($serialized) > 64000) {
            $sessionCopy = $_SESSION;
            $ignoredKeys = array();
            foreach ($_SESSION as $key => $value) {
                $size = strlen(serialize($value));
                if ($size > 1000) {
                    unset($sessionCopy[$key]);
                    $ignoredKeys[$key] = $key;
                }
            }
            $sessionCopy['z_ignored_keys_in_page_trail'] = $ignoredKeys;
            $serialized = serialize($sessionCopy);
        }
        return unserialize($serialized);
    }


    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @param array $options
     * @return ActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search($options = array())
    {
        $criteria = new CDbCriteria;
        if (strpos($this->id, 'range ') !== false) {
            $id = trim(str_replace('range ', '', $this->id));
            list($start, $end) = explode('-', $id);
            $criteria->addBetweenCondition('t.id', trim($start), trim($end));
        }
        else {
            $criteria->compare('t.id', $this->id);
        }

        $criteria->compare('t.user_id', $this->user_id);
        if (sf('limit') != 'ignore') {
            $date = date('Y-m-d', strtotime('-15 days'));
            $criteria->compare('t.created', ' > ' . $date);
            $criteria->compare('t.user_id', '<> ""');

            // ignore system users
            $lcdUserCriteria = new CDbCriteria();
            $lcdUserCriteria->compare('u2r.role_id', Role::ROLE_LCD, true);
            $lcdUserCriteria->join .= ' LEFT JOIN user_to_role u2r ON u2r.user_id=t.id AND u2r.role_id=:role_id';
            $lcdUserCriteria->params[':role_id'] = Role::ROLE_LCD;
            $lcdUsers = User::model()->findAll($lcdUserCriteria);
            foreach ($lcdUsers as $lcdUser) {
                $criteria->addCondition('t.user_id != ' . $lcdUser->id);
            }
        }
        $criteria->compare('t.created', $this->created);
        $criteria->compare('t.link', $this->link, true);

        $criteria->compare('t.app_version', $this->app_version);
        $criteria->compare('t.yii_version', $this->yii_version);
        $criteria->compare('t.audit_trail_count', $this->audit_trail_count);
        $criteria->compare('t.total_time', $this->total_time);
        $criteria->compare('t.memory_usage', $this->memory_usage);
        $criteria->compare('t.memory_peak', $this->memory_peak);
        $criteria->mergeWith($this->getDbCriteria());

        if ($this->model) {
            $criteria->distinct = true;
            $criteria->compare('t.audit_trail_count', '>0');
            //$criteria->group = 't.id';
            $criteria->join .= ' INNER JOIN audit_trail ON audit_trail.page_trail_id=t.id ';
            $criteria->compare('audit_trail.model', $this->model);
            if ($this->model_id) {
                $criteria->compare('audit_trail.model_id', $this->model_id);
            }
        }

        return new ActiveDataProvider(get_class($this), CMap::mergeArray(array(
            'criteria' => $criteria,
        ), $options));
    }

    /**
     * @return string
     */
    public function showYiiVersion()
    {
        $startPos = strpos($this->yii_version, 'yii-');
        $endPos = strpos($this->yii_version, '.r', $startPos);
        $len = $endPos - $startPos;
        $shortVersion = substr($this->yii_version, $startPos, $len);
        $shortVersion = substr($shortVersion, 4);
        $icon = l(i(au() . '/icons/comments.png'), 'javascript:void();', array('title' => $this->yii_version));
        return $icon . '&nbsp;' . $shortVersion;
    }


    /**
     * @return bool|string
     */
    public function showAppVersion()
    {
        return l(i(au() . '/icons/comments.png'), 'javascript:void();', array('title' => $this->app_version));
    }

    /**
     * @return PageTrail
     */
    public function findCurrent()
    {
        // get existing pagetrail
        if (static_id('page_trail_id')) {
            $pageTrail = PageTrail::model()->findByPk(static_id('page_trail_id'));
        }

        // create new page trail
        else {
            $pageTrail = new PageTrail();
            $pageTrail->recordPageTrail();
            app()->onEndRequest = array($pageTrail, 'updatePageTrail');
        }

        return $pageTrail;
    }

}